MySalon/Controllers/Admin/AdminPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MySalon_Master.Data;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MySalon_Master.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class AdminPanelController : Controller
    {

        private ApplicationDbContext _db;

        public AdminPanelController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Reports()
        {
            return View();
        }
    }
}

MySalon/Controllers/Admin/ManageAppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MySalon_Master.Controllers.Admin
{
    public class ManageAppointmentController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

MySalon/Controllers/Admin/ManageUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MySalon_Master.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MySalon_Master.Controllers.Admin
{
    [Authorize(Roles = "Admin")]

    public class ManageUserController : Controller
    {

        private ApplicationDbContext _db;

        public ManageUserController(ApplicationDbContext db)
        {

            _db = db;
        }
        public async Task<IActionResult> UserManagement()
        {
            return View(await _db.Users.ToListAsync());
        }

        public async Task<IActionResult> UserInfo(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _db.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

    }
}

MySalon/Views/AdminPanel/Index.cshtml
@model object

@{
    ViewBag.Title = "Admin Panel";
    Layout = "_Layout";
}

<div class="container pt-3">
    <h2>Admin Panel</h2>
    <div class="container">
        <div class="row" align="justify">
            <div class="col-sm-4">
                <div class="card" style="width: 220px; height: 150px;">
                    <div class="card-body">
                        <h4 class="card-title"><i class="fas fa-users-cog"></i> Manage Users</h4>

                        <a asp-controller="ManageUser" asp-action="UserManagement" class="btn btn-primary">View</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card" style="width: 220px; height: 150px;">
                    <div class="card-body">
                        <h4 class="card-title"><i class="fas fa-university"></i> Manage Appointments</h4>

                        <a asp-controller="ManageAppointment" asp-action="AppointmentManagement" class="btn btn-primary">View</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card" style="width: 220px; height: 150px;">
                    <div class="card-body">
                        <h4 class="card-title"><i class="fas fa-graduation-cap"></i> Manage Staffs</h4>

                        <a asp-controller="ManageStaff" asp-action="StaffManagement" class="btn btn-primary">View</a>
                    </div>
                </div>
            </div>

        </div>
        <div class="row mt-4" align="justify">
            <div class="col-sm-4">
                <div class="card" style="width: 220px; height: 150px;">
                    <div class="card-body">
                        <h4 class="card-title"><i class="fas fa-file-alt"></i> Generate Reports</h4>
                        <a asp-controller="AdminPanel" asp-action="Reports" class="btn btn-primary">View</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MySalon/Views/AdminPanel/Reports.cshtml
@model object

@{
    ViewBag.Title = "Reports";
    Layout = "_Layout";
}
<div class="container pt-3">
    <h2>Reports</h2>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Report Code</th>
            <th scope="col">Report Type</th>
            <th scope="col">Sector</th>
            <th scope="col">Availability</th>
            <th scope="col">View/Delete</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">R1</th>
            <td>Logged Users</td>
            <td>User</td>
            <td>Yes</td>
            <td><a asp-action="Reports">View</a><a>|</a><a href="#" class="removeLink">Remove</a></td>
        </tr>
        </tbody>
    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
        <a class="nav-link" asp-controller="AdminPanel" asp-action="Index"><i class="far fa-arrow-alt-circle-left"></i> Back To Admin Panel</a>
    </nav>
</div>